# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/will/Documents/AdBed_Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/will/Documents/AdBed_Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/will/Documents/AdBed_Project/CMakeFiles /home/will/Documents/AdBed_Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/will/Documents/AdBed_Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server_program

# Build rule for target.
server_program: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server_program
.PHONY : server_program

# fast build rule for target.
server_program/fast:
	$(MAKE) -f CMakeFiles/server_program.dir/build.make CMakeFiles/server_program.dir/build
.PHONY : server_program/fast

#=============================================================================
# Target rules for targets named client_program

# Build rule for target.
client_program: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_program
.PHONY : client_program

# fast build rule for target.
client_program/fast:
	$(MAKE) -f CMakeFiles/client_program.dir/build.make CMakeFiles/client_program.dir/build
.PHONY : client_program/fast

#=============================================================================
# Target rules for targets named csapp

# Build rule for target.
csapp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csapp
.PHONY : csapp

# fast build rule for target.
csapp/fast:
	$(MAKE) -f csapp/CMakeFiles/csapp.dir/build.make csapp/CMakeFiles/csapp.dir/build
.PHONY : csapp/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f classes/CMakeFiles/server.dir/build.make classes/CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f classes/CMakeFiles/client.dir/build.make classes/CMakeFiles/client.dir/build
.PHONY : client/fast

clientMain.o: clientMain.cpp.o

.PHONY : clientMain.o

# target to build an object file
clientMain.cpp.o:
	$(MAKE) -f CMakeFiles/client_program.dir/build.make CMakeFiles/client_program.dir/clientMain.cpp.o
.PHONY : clientMain.cpp.o

clientMain.i: clientMain.cpp.i

.PHONY : clientMain.i

# target to preprocess a source file
clientMain.cpp.i:
	$(MAKE) -f CMakeFiles/client_program.dir/build.make CMakeFiles/client_program.dir/clientMain.cpp.i
.PHONY : clientMain.cpp.i

clientMain.s: clientMain.cpp.s

.PHONY : clientMain.s

# target to generate assembly for a file
clientMain.cpp.s:
	$(MAKE) -f CMakeFiles/client_program.dir/build.make CMakeFiles/client_program.dir/clientMain.cpp.s
.PHONY : clientMain.cpp.s

serverMain.o: serverMain.cpp.o

.PHONY : serverMain.o

# target to build an object file
serverMain.cpp.o:
	$(MAKE) -f CMakeFiles/server_program.dir/build.make CMakeFiles/server_program.dir/serverMain.cpp.o
.PHONY : serverMain.cpp.o

serverMain.i: serverMain.cpp.i

.PHONY : serverMain.i

# target to preprocess a source file
serverMain.cpp.i:
	$(MAKE) -f CMakeFiles/server_program.dir/build.make CMakeFiles/server_program.dir/serverMain.cpp.i
.PHONY : serverMain.cpp.i

serverMain.s: serverMain.cpp.s

.PHONY : serverMain.s

# target to generate assembly for a file
serverMain.cpp.s:
	$(MAKE) -f CMakeFiles/server_program.dir/build.make CMakeFiles/server_program.dir/serverMain.cpp.s
.PHONY : serverMain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... server_program"
	@echo "... client_program"
	@echo "... csapp"
	@echo "... server"
	@echo "... client"
	@echo "... clientMain.o"
	@echo "... clientMain.i"
	@echo "... clientMain.s"
	@echo "... serverMain.o"
	@echo "... serverMain.i"
	@echo "... serverMain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

